name: Frontend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

jobs:
  run-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: caches npm
      id: restore-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('**/package-lock.json') }}
          npm-

    - name: Install dependencies
      run: npm ci

    - name: Run test
      run: CI=true npm test

  run-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: caches npm
      id: restore-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('**/package-lock.json') }}
          npm-

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint
  
  build:
    needs: [run-test, run-lint]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: caches npm
      id: restore-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('**/package-lock.json') }}
          npm-

    - name: Install dependencies
      run: npm ci

    - name: Run test
      run: CI=true npm test

    # build 
    - name: build image
      run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag mp-frontend:latest .
      
