name: Frontend Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: cd starter/frontend && npm ci

    - name: Run test
      run: cd starter/frontend && CI=true npm test


  run-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: cd starter/frontend && npm ci

    - name: Run lint
      run: cd starter/frontend && npm run lint
  
  build:
    needs: [run-test, run-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        uses: actions/checkout@v3
        run: |
          cd starter/frontend
          docker build -t mp-frontend:$GITHUB_SHA .



      
